name: Compilar TM Launcher por ZIP

on:
  push:
    paths:
      - 'project.zip'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o Repositório
        uses: actions/checkout@v4

      - name: Verificar e Descompactar o project.zip
        run: |
          if [ -f "project.zip" ]; then
            echo "project.zip encontrado com sucesso!"
            unzip project.zip -d source_code
          else
            echo "Erro: project.zip não foi encontrado na raiz do repositório!"
            exit 1
          fi

      - name: Configurar o Java (JDK 17)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Compilar o APK com o Gradle
        run: |
          cd source_code
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Salvar o APK gerado
        uses: actions/upload-artifact@v4
        with:
          name: tm-launcher-apk
          path: source_code/app/build/outputs/apk/debug/*.apk
